# Generated by Django 5.2.5 on 2025-08-18 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vehicle_no', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recovery_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_ltr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_tk', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('toll', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('repair', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('police', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('without_doc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('posted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
