# Generated by Django 5.2.5 on 2025-08-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='trip_no',
            field=models.CharField(default='TRIP000000001', editable=False, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
