# Generated by Django 5.2.5 on 2025-08-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_trip_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='food',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='fuel_ltr',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='fuel_tk',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='police',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='recovery_fare',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='repair',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='toll',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='without_doc',
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Posted', 'Posted')], default='New', max_length=10),
        ),
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('period', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Daily', max_length=10)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_costs', to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='VariableCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recovery_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fuel_tk', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('toll', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('repair', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('police', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('without_doc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variable_cost', to='shipments.shipment')),
            ],
        ),
    ]
