# Generated by Django 5.2.5 on 2025-08-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_remove_shipment_fare_remove_shipment_food_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-trip_no']},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='trip_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
