# Generated by Django 5.2.5 on 2025-08-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_fuel_ltr_alter_shipment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fuel_ltr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Posted', 'Posted')], default='New', max_length=20),
        ),
    ]
