# Generated by Django 5.2.5 on 2025-08-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_alter_shipment_destination_alter_shipment_fuel_ltr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Fixed Cost Configuration',
                'verbose_name_plural': 'Fixed Cost Configuration',
            },
        ),
        migrations.DeleteModel(
            name='FixedCost',
        ),
    ]
