# Generated by Django 5.2.5 on 2025-08-18 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_fixedcostconfig_delete_fixedcost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcostconfig',
            options={},
        ),
        migrations.AddField(
            model_name='shipment',
            name='fixed_insurance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='fixed_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fuel_ltr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
