# Generated by Django 5.2.5 on 2025-08-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_alter_fixedcostconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='fixed_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fixed_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fuel_ltr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Posted', 'Posted')], default='New', max_length=20),
        ),
    ]
