# Generated by Django 5.2.5 on 2025-08-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_shipment_expenses_shipment_freight_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='insurance_snapshot',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='salary_snapshot',
        ),
    ]
