# Generated by Django 5.2.5 on 2025-08-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_remove_shipment_insurance_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='freight_charge',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='revenue',
        ),
    ]
