# Generated by Django 5.2.5 on 2025-08-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_remove_shipment_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='fixed_insurance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fixed_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fuel_ltr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
