# Generated by Django 5.2.5 on 2025-08-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_alter_shipment_fixed_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_from', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fixed_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fixed_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='FixedCostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_costs', to='shipments.shipment')),
            ],
        ),
    ]
