# Generated by Django 5.2.5 on 2025-08-19 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_fixedcost_alter_shipment_fixed_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcostconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
