# Generated by Django 5.2.5 on 2025-08-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_fixedcostconfig_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcostconfig',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
