# Generated by Django 5.2.5 on 2025-08-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0016_alter_fixedcostconfig_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcostrecord',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fixedcostrecord',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
