# Generated by Django 5.2.5 on 2025-08-19 19:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0017_alter_fixedcostrecord_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='prorated_insurance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='prorated_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
