# Generated by Django 5.2.5 on 2025-08-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0018_shipment_prorated_insurance_shipment_prorated_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='insurance_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='salary_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
