# Generated by Django 5.2.5 on 2025-08-20 06:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0019_shipment_insurance_snapshot_shipment_salary_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcost',
            name='depriciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fixedcostconfig',
            name='depriciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shipment',
            name='depriciation_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='fixed_depriciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shipment',
            name='prorated_depriciation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
