# Generated by Django 5.2.5 on 2025-08-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0020_fixedcost_depriciation_fixedcostconfig_depriciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='vehicle_owner',
            field=models.CharField(default='GBFML', max_length=50),
            preserve_default=False,
        ),
    ]
