# Generated by Django 5.2.5 on 2025-08-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0021_shipment_vehicle_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='qty',
        ),
    ]
