# Generated by Django 5.2.5 on 2025-08-21 09:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0022_remove_shipment_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='total_cost_calculated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
