# Generated by Django 5.2.5 on 2025-08-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0023_shipment_total_cost_calculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
