# Generated by Django 5.2.5 on 2025-08-21 14:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0025_alter_shipment_depriciation_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcost',
            options={},
        ),
        migrations.RenameField(
            model_name='fixedcost',
            old_name='depriciation',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='salary',
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='name',
            field=models.CharField(choices=[('salary', 'Salary'), ('insurance', 'Insurance'), ('depriciation', 'Depreciation')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_cost_entries', to='shipments.shipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixedcostrecord',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_cost_records', to='shipments.shipment'),
        ),
        migrations.AlterField(
            model_name='fixedcostrecord',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
