# Generated by Django 5.2.5 on 2025-08-21 16:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0026_alter_fixedcost_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedcost',
            old_name='value',
            new_name='depreciation',
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='name',
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_cost', to='shipments.shipment'),
        ),
    ]
