# Generated by Django 5.2.5 on 2025-08-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0027_rename_value_fixedcost_depreciation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedcost',
            old_name='depreciation',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='salary',
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='name',
            field=models.CharField(choices=[('salary', 'Salary'), ('insurance', 'Insurance'), ('depriciation', 'Depreciation')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_cost_entries', to='shipments.shipment'),
        ),
    ]
