# Generated by Django 5.2.5 on 2025-08-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0028_rename_depreciation_fixedcost_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixedcost',
            unique_together={('shipment', 'name')},
        ),
    ]
