# Generated by Django 5.2.5 on 2025-08-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0031_alter_fixedcost_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcost',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_costs', to='shipments.shipment'),
        ),
    ]
