# Generated by Django 5.2.5 on 2025-08-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0032_alter_fixedcost_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='fuel_consumption',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='remaining_fuel',
            field=models.FloatField(default=0),
        ),
    ]
