# Generated by Django 5.2.5 on 2025-08-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0033_shipment_fuel_consumption_shipment_remaining_fuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='fuel_consumption',
        ),
    ]
