# Generated by Django 5.2.5 on 2025-08-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0034_remove_shipment_fuel_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='fuel_consumption',
            field=models.FloatField(default=0),
        ),
    ]
