# Generated by Django 5.2.5 on 2025-08-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0036_vehiclemaintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemaintenance',
            options={},
        ),
    ]
