# Generated by Django 5.2.5 on 2025-08-23 16:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0037_alter_vehiclemaintenance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
