# Generated by Django 5.2.5 on 2025-08-24 16:21
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0039_alter_shipment_maintenance_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='year',
            field=models.PositiveIntegerField(default=2025),  # ✅ integer year
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemaintenance',
            unique_together={('vehicle_no', 'month', 'year')},
        ),
    ]

