# Generated by Django 5.2.5 on 2025-08-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0040_vehiclemaintenance_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclemaintenance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='total_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='year',
            field=models.IntegerField(),
        ),
    ]
