# Generated by Django 5.2.5 on 2025-08-24 17:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0041_alter_vehiclemaintenance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='prorated_maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
