# Generated by Django 5.2.5 on 2025-08-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0042_shipment_prorated_maintenance_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemaintenance',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemaintenance',
            unique_together={('vehicle_no', 'month', 'year')},
        ),
    ]
