# Generated by Django 5.2.5 on 2025-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0043_alter_vehiclemaintenance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcostconfig',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='fixedcostconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fixedcostconfig',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixedcostconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
