# Generated by Django 5.2.5 on 2025-08-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0044_fixedcostconfig_month_fixedcostconfig_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcostconfig',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='name',
            field=models.CharField(choices=[('salary', 'Salary'), ('insurance', 'Insurance'), ('depriciation', 'Depriciation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fixedcostconfig',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default='2025'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixedcostconfig',
            name='year',
            field=models.PositiveIntegerField(default='2025'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fixedcostconfig',
            unique_together={('month', 'year')},
        ),
    ]
