# Generated by Django 5.2.5 on 2025-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0046_fixedcostconfig_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='arrival_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='trip_duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Duration in days (same day = 1)'),
        ),
    ]
